// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFfFUzZmIiNFyL-KrfczC4DmfbONazpxI',
    appId: '1:895111842702:web:7113dc0e9f6619e83072df',
    messagingSenderId: '895111842702',
    projectId: 'onemovieticketbehaceproject',
    authDomain: 'onemovieticketbehaceproject.firebaseapp.com',
    storageBucket: 'onemovieticketbehaceproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1U3Pn47wwmchCkJFyA5QgIxliZDAwfo',
    appId: '1:895111842702:android:8e5bfbd280936d0f3072df',
    messagingSenderId: '895111842702',
    projectId: 'onemovieticketbehaceproject',
    storageBucket: 'onemovieticketbehaceproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnvXczi4QVL9BWwV75GOiJMQXkvtA8bo',
    appId: '1:895111842702:ios:4c29b4b1858ec5c63072df',
    messagingSenderId: '895111842702',
    projectId: 'onemovieticketbehaceproject',
    storageBucket: 'onemovieticketbehaceproject.appspot.com',
    iosClientId: '895111842702-o8ns8kcm5t6ubli1fri5a7a5gol72qnd.apps.googleusercontent.com',
    iosBundleId: 'com.onemovieticket.onemovieticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnvXczi4QVL9BWwV75GOiJMQXkvtA8bo',
    appId: '1:895111842702:ios:4c29b4b1858ec5c63072df',
    messagingSenderId: '895111842702',
    projectId: 'onemovieticketbehaceproject',
    storageBucket: 'onemovieticketbehaceproject.appspot.com',
    iosClientId: '895111842702-o8ns8kcm5t6ubli1fri5a7a5gol72qnd.apps.googleusercontent.com',
    iosBundleId: 'com.onemovieticket.onemovieticket',
  );
}
